name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up
        uses: actions/setup-python@v2
        with:
              python-version: '3.x'

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: Run
        run: python -m unittest discover
        
